# 指定环境为dev
# 生产环境：java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:d:/testdb
    username: sa
    password: 123456

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      #http://localhost:8080/h2-console
      path: /h2-console
      enabled: true
  messages:
      basename: i18n/messages
logging:
  level:
    root: warn