nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.discovery.server-addr}/?username=${nacos.discovery.username}&password=${nacos.discovery.password}
  scan:
    base-packages: com.ynthm.dubbo
product:
  service:
    version: 1.0.0