spring:
  application:
    name: inventory-service
  profiles:
    active: dev
nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos
    type: yaml
    data-id: inventory-service.yaml
